### ISSUE TITLE
List assignment with ternary operator

### ISSUE THREAD

**Issue by matteomazza91** [MutabilityDetector/MutabilityDetector#111]
I have found a **False negative**: I wrote a User class that is immutable but the detector doesn't think it is.
I directly provide a piece of code:

given that `this.roles` is a private final field and no setter methods are defined
if I write this code in the constructor, the class is correctly recognized IMMUTABLE.

    if (roles == null) {
      this.roles = null;
    } else {
      this.roles = Collections.unmodifiableList(new ArrayList<String>(roles));
    }

but, if I write this code instead:
    this.roles = (roles == null ? null : Collections.unmodifiableList(new ArrayList<String>(roles)));
the check fail with this Exception:

    Expected:[...].User to be IMMUTABLE
     but: [...].User is actually NOT_IMMUTABLE
    Reasons:
        Field is not a wrapped collection type. You can use this expression: Collections.unmodifiableList(new ArrayList<String>(roles)) [Field: roles at [...].User(User.java:1)]
    Allowed reasons:
        None.
	at org.mutabilitydetector.unittesting.internal.AssertionReporter.assertThat(AssertionReporter.java:48)
	at org.mutabilitydetector.unittesting.MutabilityAsserter.assertImmutable(MutabilityAsserter.java:127)
	at org.mutabilitydetector.unittesting.MutabilityAssert.assertImmutable(MutabilityAssert.java:672)
	at [...]TestUser.theUserIsImmutable(TestUser.java:92)

if I need to provide more info, please let me know.

**Comment by Grundlefleck** [comment]
Thanks for raising. I've easily reproduced in a [test case](https://github.com/MutabilityDetector/ClientOfMutabilityDetector/commit/43160e3c311d89fafb7eae9c9d72a4e973e13038).

I can't give an ETA on a fix right now, but I'll start taking a look.

**Comment by rohansuri** [comment]
Hi @Grundlefleck could I take this issue up?
I've started debugging my way through and understand that a smarter check (or change in what is being passed to it's ctor) is required in `CollectionTypeWrappedInUnmodifiableIdiomChecker` 
Probably starting with what is the `typeAssignedToField` ctor arg in case of the ternary operator.

I hope I'm in the right direction

**Comment by Grundlefleck** [comment]
Hey @rohansuri,

You can absolutely take this issue up :) I think there is a minimal fix which addresses the immediate issue (that looks something like the change [here](https://github.com/MutabilityDetector/MutabilityDetector/pull/112/files) but if you have an idea for a more advanced analysis then I'm very keen to see it. I think it would be good to be able to point to one or both of the branches if there is a problem, I believe it's better to see all issues upfront rather than go through a fix -> test -> fix -> test cycle.

**Comment by Grundlefleck** [comment]
This has been addressed by #112 and will be in the next release.

Many thanks to @sband for his contribution.

@rohansuri although this issue is fixed, I'm still very open to hearing your thoughts on improvements to the analysis.
