### ISSUE TITLE
com.google.common.primitives.ImmutableDoubleArray, ImmutableIntArray, ImmutableLongArray

### ISSUE THREAD

**Issue by luke777** [MutabilityDetector/MutabilityDetector#114]
Would it be possible to add 
com.google.common.primitives.ImmutableDoubleArray, ImmutableIntArray, ImmutableLongArray
to the list of Guava hardcoded immutable classes?

**Comment by Grundlefleck** [comment]
Yup, going by the class names at least those should be on the list. Do you
fancy creating a PR? "No" is a fine answer :)

**Comment by shauryapatel27** [comment]
Hi I would like to get started on contributing to this project with this change if it is still open. I have significant experience with Java and would like to work on this. Please let me know if this issue is still open.

**Comment by Grundlefleck** [comment]
The issue is still open, PR very welcome.

**Comment by logan-lieou** [comment]
What even is PR and is this issue still open I am very new

**Comment by Grundlefleck** [comment]
Hi @logan-lieou ,

PR means "Pull Request", and it basically means "I suggest these changes, will you accept them?". A lot of the times changes are functional changes to the code (bug fixes, enhancements) but they can also be things like: adding documentation; refactoring (changing code to be easier to understand, without changing what it does); or even correcting spelling mistakes. 

If you are interested, I could find a beginner's guide on creating Pull Requests, then create an issue specifically for you to practice your first pull request on. Are you interested? Then once you're comfortable with the process of creating a Pull Request, we could focus on fixing this issue?

**Comment by emmahastings** [comment]
Hey,

Sorry if I stepped on anyones toes here but I had started looking at this issue yesterday and just thought I'd see it through. I'd been playing around with the using the code to analyse some of my own work. I have created a PR if you are interested: https://github.com/MutabilityDetector/MutabilityDetector/pull/139.

Thanks,
Emma

**Comment by Grundlefleck** [comment]
@emmahastings no toe-stepping as far as I can see. I can create an abundance of tasks to work on, it's getting interested, motivated people like yourself that's the constraint :)

Thank you for your fix!
