### ISSUE TITLE
Releases remarks

### ISSUE THREAD

**Issue by lrozenblyum** [MutabilityDetector/MutabilityDetector#118]
Hi there! Thanks for the great project!

I'm working on updating some Maven dependencies and it looks Mutability Detector 0.10.1 has been found at Maven central.

However I couldn't find a changelog and GitHub releases seem to be a little bit not up-to-date:

1) http://mutability-detector.blogspot.com/ - mentions 0.9.6
2) https://github.com/MutabilityDetector/MutabilityDetector/releases - this page also shows 0.9.6 as the latest release
3) https://github.com/MutabilityDetector/MutabilityDetector/tags - this one shows 0.10.0

The 3'd issue means that 0.10.1 release has no tag at all (which is usually a good idea to be created).

It would be nice to update the information about the releases.

**Comment by Grundlefleck** [comment]
Hi @lrozenblyum. I've added a Tag and a Release, and changed the Getting started information in the README to point to 0.10.1. I've chosen not to do a blog entry, I think I'll save that for significant releases that require descriptions. 

Many thanks for reporting!

**Comment by lrozenblyum** [comment]
Thanks @Grundlefleck!
