### ISSUE TITLE
Include Java 8 date-time API into JdkConfiguration

### ISSUE THREAD

**Issue by remal** [MutabilityDetector/MutabilityDetector#159]
Please include Java 8 date-time API into `JdkConfiguration`. Almost all `java.time.**` classes are immutable or at least effectively immutable, so they can be included in `JdkConfiguration`.

**Comment by remal** [comment]
At least these types can be considered immutable:
- `java.time.Duration`
- `java.time.Instant`
- `java.time.LocalDate`
- `java.time.LocalDateTime`
- `java.time.LocalTime`
- `java.time.OffsetDateTime`
- `java.time.OffsetTime`
- `java.time.Period`
- `java.time.Year`
- `java.time.YearMonth`
- `java.time.ZoneId`
- `java.time.ZoneOffset`
- `java.time.ZonedDateTime`
- `java.time.format.DateTimeFormatter`

**Comment by Grundlefleck** [comment]
Hey @remal thanks for raising. Any interest in contributing or do you just want to see it get done?

**Comment by remal** [comment]
@Grundlefleck Due to personal reasons I'll be able to contribute only at the end of March. So I'll be happy if someone do it.

If you need some help here, I'll see how I can help closer to the end of March.

**Comment by Grundlefleck** [comment]
No problem at all, and no need to explain. I'll make it available for any
newcomers who may wish to contribute and if nobody takes it up I'll do it
shortly.

Thanks for raising.

**Comment by bharatbhasin** [comment]
Created a pull request for it: https://github.com/MutabilityDetector/MutabilityDetector/pull/164

**Comment by Grundlefleck** [comment]
Fixed thanks to @bharatbhasin.

**Comment by Grundlefleck** [comment]
https://twitter.com/Grundlefleck/status/1299053448969818112
