### ISSUE TITLE
Support List.of et al as creating immutable collections

### ISSUE THREAD

**Issue by Grundlefleck** [MutabilityDetector/MutabilityDetector#169]
Java 11 (I think) introduced List.of() methods that return immutable collections. Mutability Detector should understand that calls to this method will produce an immutable collection, so that if they are assigned to a field of type List, it's not considered mutable.

List.of happens to be the only one I mentioned, there is also, at least Set.of, I'm not sure if there are others in JDK11. We should support them all.

**Comment by fma1** [comment]
Hello. I would like to work on this as formal verification of correctness is of high interest to me.

Hmm, I suppose I am still trying to figure out how the library exactly works. I was looking at the `assertImmutable()` method and have gotten to `AllChecksRunner` which seems to run a bunch of mutability checkers. So it seems I would need to write a new class that extends `AsmMutabilityChecker`.

**Comment by Grundlefleck** [comment]
Hi @fma1 and thanks for your interest.

For this issue in particular, I was expecting to look into `JdkConfiguration` and add hardcoded definitions that declare e.g. List.of produces an immutable container type. 

I wasn't expecting formal verification of correctness, as I'd expect that's really difficult, but I'd be keen to hear more if you have ideas on how to achieve that.

**Comment by fma1** [comment]
Hi @Grundlefleck. I suppose I misspoke. What I meant is this sort of project really interests me. Actual formal verification of correctness generally involves dealing with the Abstract Syntax Tree, which is something that Lombok does. From what you said, it seems like this issue is simpler than I thought. I'll try to start working on this later today so hopefully I should be able to raise a PR soon.

**Comment by Grundlefleck** [comment]
Fixed with #175

**Comment by thjaeckle** [comment]
This is not yet released, is it?

**Comment by Grundlefleck** [comment]
Aw jeez, no, I went and forgot that part.

Just pushed 0.10.4, it should land in Maven central within the next few hours. Thanks for the reminder @thjaeckle !

**Comment by Grundlefleck** [comment]
https://twitter.com/Grundlefleck/status/1299053448969818112

I'd have credited you if I knew your Twitter handle @fma1. Thanks again.

**Comment by fma1** [comment]
You're welcome. My twitter handle is FredMa7153 but it's perfectly fine that you didn't mention it. I don't use Twitter that actively although I've been looking to change that.
