### ISSUE TITLE
RFE: Configurable strictness

### ISSUE THREAD

**Issue by ThrawnCA** [MutabilityDetector/MutabilityDetector#61]
As mentioned in the documentation, the analysis is quite strict. Is it reasonable to make this more configurable?

For example, if a class is immutable as it stands, but is not final, then some projects might wish to consider that immutable.

**Comment by ThrawnCA** [comment]
Looks like this is at least partly achieved when configuring assertions.

**Comment by Grundlefleck** [comment]
Hi @ThrawnCA,

Firstly apologies for taking so long to respond.

Were you able to configure the strictness in a way that met your requirements? For example, a non-final class can be allowed with `AllowedReason.allowingForSubclassing()`. Are there any other specific examples you need to cater for?

**Comment by Grundlefleck** [comment]
Sorry, I can't make any progress on your issue without more detail. Please feel free to open if you can provide clarifications/suggestions.
