### ISSUE TITLE
Source files without license headers

### ISSUE THREAD

**Issue by puntogil** [MutabilityDetector/MutabilityDetector#81]
Hi
The following source files are without license headers:

./src/test/benchmarks/org/mutabilitydetector/benchmarks/mutabletofield/generic/HasFieldUsingGenericTypeOfClass.java
./src/test/benchmarks/org/mutabilitydetector/benchmarks/mutabletofield/generic/HasFieldOfGenericType.java

Please, confirm the licensing of code and/or content/s, and add license headers
https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Clarification

Thanks in advance
Regards

**Comment by Grundlefleck** [comment]
Those source files, like all other source files, are under Apache 2.0 license.

I'm going to offer fixing the license headers for newcomers (with the up-for-grabs tag), so they may not have an Apache 2.0 header added to them immediately, but they will at some point.

@puntogil may I ask, what is your interest in seeing these files licensed? I know they should be, but they are only test files that are not part of the main program, so wondering if they are preventing you from doing something? Or if you now just have a cool GitHub scraper that detects files with missing licenses? :-D

**Comment by puntogil** [comment]
Hi
if i want import this library in Fedora distributions then i should fix all License issues as reported in the previous link. In Fedora we use some tools to avoid these issues.
Again thanks

**Comment by jagan387** [comment]
I'm new here, and wanted to start with this issue to start with & get around the code base. This issue seems to be fixed in the latest code. Why is this still open?

**Comment by Grundlefleck** [comment]
@jagan387 my mistake. Closing now, thanks for pointing it out.
