### ISSUE TITLE
Replace Guava with Java 8

### ISSUE THREAD

**Issue by Grundlefleck** [MutabilityDetector/MutabilityDetector#89]
0.9.6 is the last release which will support being executed on pre-Java 8 JVMs, so we are now free to use Java 8 features. Currently, MutabilityDetector includes the Guava library as part of it's shaded jar. The less dependencies in this jar the better, and there's a decent chance one can be removed. I can't quite remember everything Guava is used for, but it's possible that it's limited to Optional, Function/Predicate, and FluentIterable, which can all be replaced by Java 8 features*. Also, it will mean we can remove some [icky](https://github.com/MutabilityDetector/MutabilityDetector/blob/master/src/main/java/org/mutabilitydetector/config/GuavaConfiguration.java#L27) code that's a direct result of including Guava in the jar.

This issue will be completed when Guava can be removed from the classpath, or closed as not worth it, if it's found that not everything can be reasonably replaced by Java 8 features.

* not that Guava doesn't have lots of other cool and useful stuff, I'm not saying it's bad, just that usage is pretty limited.

**Comment by talflon** [comment]
I did a quick search, and Guava isn't just used for Java 8 features in your project. It's also used for immutable collections classes (!), and some other convenience functions like `Predicates` and `Objects`. All of those could be replaced, but do you actually want them to be? Plus, you use `ClassPath`, which sounds non-trivial to replace.

Another thing you use that could be replaced by Java 8 features is `Joiner`.

**Comment by Grundlefleck** [comment]
Hey, thanks for looking!

ClassPath I think comes from another dependency ("Classpath Explorer") and
isn't part of Guava. I forgot about the use of immutable collections, d'oh.
Those alone are probably worth keeping Guava for, unless they can be easily
replaced with unmodifiable wrappers.

We could probably at least replace anonymous instances of Guava
Function/Predicate with JDK 8 lambdas. Would you be interested in making
that change?


On 6 Dec 2016 4:10 a.m., "Daniel Getz" <notifications@github.com> wrote:

I did a quick search, and Guava isn't just used for Java 8 features in your
project. It's also used for immutable collections classes (!), and some
other convenience functions like Predicates and Objects. All of those could
be replaced, but do you actually want them to be? Plus, you use ClassPath,
which sounds non-trivial to replace.

Another thing you use that could be replaced by Java 8 features is Joiner.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/MutabilityDetector/MutabilityDetector/issues/89#issuecomment-265055766>,
or mute the thread

**Comment by talflon** [comment]
Sure, I'll see what I can do.

**Comment by talflon** [comment]
You have a lot of constants that are `Functions`. As I change them from Guava to Java 8, I've been deleting ones that seem unnecessary (because they correspond to method references, or very simple lambdas). But what about the public ones? Were they public only so that they could be used between packages, or do you actually want them to stay?

---------------------

Since it sounds like Guava's staying for now, do you have a style preference between Guava's static `transform()` methods and the equivalent `Stream` code? For `Iterable` the Guava code is much cleaner:

    Iterables.transform(origIterable, x -> y)

    StreamSupport.stream(origIterable.spliterator(), false)
        .map(x -> y)
        .collect(Collectors.toList())

([I am not making this up.](http://stackoverflow.com/a/23936723/3004881) IDEA prompts me to auto-change the first code to the second code. Maybe I'm being too picky, but putting `false` to mean "the default" is super unreadable for me.)

The stream version can be a little cleaner for anything that extends `Collection`, though:

    origCollection.stream()
        .map(x -> y)
        .collect(Collectors.toList())

**Comment by Grundlefleck** [comment]
I believe public Function constants are only public to be used between packages. I'm pretty confident they can be removed. Because it uses the Maven shade plugin to repackage classes into the jar, if a library user referenced the constants they would be of type `org.mutabilitydetector.repackaged.com.google.base.Function`, and that wouldn't interact well if they tried to use it against a real Guava.

**Comment by Grundlefleck** [comment]
In terms of Iterable, yeah, I don't like the Stream version compared to Guava either. I wonder how much the choice to use Iterable was because of Guava, and whether it makes sense to use Collection. For example, every Iterable that's created can probably traced back to Mutability Detector's own code where it instantiates a concrete collection type, so is it worth having it as Iterable? I'm not sure.

Go for whatever you think is the cleanest and most readable, we don't need to decide on that just now. That okay?

**Comment by talflon** [comment]
The doc for `ConfigurationBuilder.mergeHardcodedResultsFrom()` says:

> Where the AnalysisResult for a class is found in both Configurations, the result from otherConfiguration will replace the existing result in this Configuration.

But in your implementation, and the `mergeReplacesExistingHardcodedResultForClassWithCurrentHardcodedResult` test, it's the opposite—the result is not replaced. Which should it be?

**Comment by Grundlefleck** [comment]
Whoops. Whatever the public documentation says is how it should work. Shows
how much that feature is needed :)

**Comment by talflon** [comment]
OK, it's a simple fix anyhow. I'm new to pull requests; should I fix that as a separate commit in the same pull request? Or do two pull requests?

**Comment by Grundlefleck** [comment]
If you don't mind the bit of effort, a new pull request please.

**Comment by talflon** [comment]
OK, I created issue #93 for this.

**Comment by rockydcoder** [comment]
I was going through this project, which I hope would be my first OSS PR. If the above branch is merged, why is this issue still open?

**Comment by Grundlefleck** [comment]
@rockydcoder most likely it was a plain old mistake on my part :) closing now, thanks for the reminder.
