### ISSUE TITLE
toString detector do not find a field

### ISSUE THREAD

**Issue by gualtierotesta** [MutabilityDetector/MutabilityDetector#96]
Hi,

the hasValidBeanToString() fails on a field named **aStr** (it seems it looks for **AStr** instead).

Java version: 1.8.0_112, vendor: Oracle Corporation
MutabilityDetector: 0.9.6

Message is 
```
java.lang.AssertionError: 
Expected: (bean class with a valid no-args constructor and bean with valid setter and getter methods for all properties and bean with all properties influencing hashCode and bean with all properties compared in equals and bean with toString() describing class name and all properties)
     but: bean with toString() describing class name and all properties bean of type "it.gualtierotesta.testsolutions.general.beans.LombokBean" had an invalid toString() method. It did not produce the property name "AStr", actual output "LombokBean(aStr=69cea64a-a26b-479c-87ca-f1626677bf54, anInt=0)"
```

Class code:
```
@Data
public class LombokBean implements Serializable {

    String aStr;
    int anInt;

}
```

Test class code:
```
 @Test
    public void testClassIsGoodBean() {
        assertThat(LombokBean.class, allOf(
                hasValidBeanConstructor(),
                hasValidGettersAndSetters(),
                hasValidBeanHashCode(),
                hasValidBeanEquals(),
                hasValidBeanToString()  // Error is here !
        ));
    }
```

Complete project can be found at https://github.com/gualtierotesta/test-solutions module general class LombokBean.

Note: I know there is no meaning to test Lombok generated toString() method but may be the problem will raise also on non Lombok generated toString methods.

**Comment by Grundlefleck** [comment]
Hi @gualtierotesta, I think you might have the wrong github project. It looks like your error is in the bean-matchers library, and the repo you're looking for is here: https://github.com/orien/bean-matchers

Let me know if I've got that wrong and the error is related to Mutability Detector. And please don't hesitate to raise any other issues! :)

**Comment by gualtierotesta** [comment]
@Grundlefleck You are perfectly right. I added the issue to the wrong project. I'm really sorry.
By the way, I've found your project very useful and I will adopt it in my company projects. Many thanks.

**Comment by Grundlefleck** [comment]
No need to apologise :) 

Great to hear you're finding Mutability Detector useful, if you can think of any features that would help you, don't be shy!
