### ISSUE TITLE
Collection fields with generic types of primitive array result in NullPointerException

### ISSUE THREAD

**Issue by Grundlefleck** [MutabilityDetector/MutabilityDetector#98]
When a class has a field like:

  `private final List<byte[]> myByteList = new ArrayList<>();`

The `CollectionField` class, and therefore the `MutableTypeToFieldChecker` fails to recognise the generic types of the collection, and return null, instead of an `[Z`.

There are two tests that demonstrate this:
 - `CollectionFieldTest.recognisesPrimitiveArrayAsGenericTypeOfCollectionField`
 - `WellKnowJavaTypesTest.PNGMetadata`

This issue will be complete when those two tests pass, and there's no longer an NPE thrown when analysing rt.jar.

**Comment by vik4es** [comment]
Hi! 
I've tried to fix this issue in pull request Issue_98_fix

Check please if fix is acceptable

**Comment by Grundlefleck** [comment]
The fix looked acceptable to me. Good job @vik4es :)
